### PR TITLE
Stop generating compiler META files for OCaml 5.0+

### PR DESCRIPTION
**Pull request by dra27**
This is an update of #45, compatible with the latest version pushed to ocaml/ocaml#11007. The current proposal is that from OCaml 5.0.0~alpha1, the compiler installs its own `META` files in directories under the Standard Library directory.

The previous version was not able to guarantee the operation of Dune or opam's `ocaml-system` because there wasn't a mechanism for reliably determining the location of the compiler's `META` files. The latest revision proposes that the compiler's `META` are therefore _always_ installed in the same place, with Dune and ocamlfind using that fact to change their default search paths for packages accordingly.

This PR, therefore:
- Reverts the addition of the `runtime_events` `META` file, since findlib never needs to build it
- Updates the detection machinery in `configure` never to generate `META` files for the compiler for 5.0+
- Adds the Standard Library directory to the start of `path` in `findlib.conf` (unless findlib is configured with `-sitelib $(ocamlc -where)` as this is then unnecessary)

The last part requires a small tweak for Windows to take advantage of the fact that `cygpath` knows how to translate `PATH`-style variables.

### CODE REVIEW

**Comment by dra27** [comment]
@gerdstolpmann - OCaml 5.0.0~alpha1 is out. Would it be possible to have a 1.9.6 release with this and https://github.com/ocaml/ocamlfind/pull/54, please?

**Comment by gerdstolpmann** [comment]
@dra27 This looks good, just one suggestion for improvement. I can release on this weekend (btw., sorry for the delay, it was a very busy year so far).

**Comment by dra27** [comment]
No problem at all, @gerdstolpmann! Rebased and updated. findlib hasn't supported OCaml 3.x since 1.8.0 when 23cafe184a5899946599ceda4583e3ee32cef69a introduced a use of `String.map` (which is a 4.00 stdlib function). I've hardened the `configure` script as suggested for OCaml 3.x, regardless - and also fixed a typo from an earlier OCaml 5 related change.

findlib has been 3.08+ since findlib 1.1! It's up to you, but 3.08-3.12 can be "re-supported" with these three commits which are in the "old-compilers" branch of my fork:
- https://github.com/dra27/ocamlfind/commit/0875ed7c9a746c926399755a6b0760d9d275756e - removes the use of lazy patterns (which were introduced in OCaml 3.11)
- https://github.com/dra27/ocamlfind/commit/c815a3a5f7c874ca0c6fbe2daa1fda7b7354dd8b - removes the use of `String.map` and `Lazy.from_fun` which were both introduced in OCaml 4.00
- https://github.com/dra27/ocamlfind/commit/5c51651daf252aca8a040bef4bd4eaa32cb869d1 uses the same technique as used for `ocamlc -opaque` for `ocmalopt -g` (which was introduced in OCaml 3.10)

**Comment by gerdstolpmann** [comment]
Nice! I'll apply these patches.

**Pull request merged**
